// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARvFXXyNuV6_lUBgXvxYv_sexOjoCkqwI',
    appId: '1:460863079302:web:355352cbb030d58ec1a207',
    messagingSenderId: '460863079302',
    projectId: 'myadventure-453a8',
    authDomain: 'myadventure-453a8.firebaseapp.com',
    storageBucket: 'myadventure-453a8.appspot.com',
    measurementId: 'G-2SSTGWLY8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0XSchRID2QDh68o8rHeGGPiXGTyY3B00',
    appId: '1:460863079302:android:139ae784f8571e40c1a207',
    messagingSenderId: '460863079302',
    projectId: 'myadventure-453a8',
    storageBucket: 'myadventure-453a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATgLCNAtFW29r7Kc1d2LuJ0bJyFt5_lIc',
    appId: '1:460863079302:ios:7831628ec0bcf173c1a207',
    messagingSenderId: '460863079302',
    projectId: 'myadventure-453a8',
    storageBucket: 'myadventure-453a8.appspot.com',
    iosBundleId: 'com.example.travelProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARvFXXyNuV6_lUBgXvxYv_sexOjoCkqwI',
    appId: '1:460863079302:web:61647011ae12dd54c1a207',
    messagingSenderId: '460863079302',
    projectId: 'myadventure-453a8',
    authDomain: 'myadventure-453a8.firebaseapp.com',
    storageBucket: 'myadventure-453a8.appspot.com',
    measurementId: 'G-GN55S3GV0N',
  );
}
